### ISSUE TITLE
.deb package causes app launcher item with name and note "Haveno" instead of a "RetoSwap"

### ISSUE THREAD

**Issue by slrslr** [retoaccess1/haveno-reto#47]
On Linux Debian 12 with KDE desktop (all latest stable), when I install RetoSwap .deb file v1.0.15 I have found RetoSwap launcher in the application menu named as Haveno and note is also Haveno.
It should mention Haveno (possibly in description or note), but in the name should be RetoSwap. not Haveno ?

Btw. launched application has "Haveno-reto" in a window title. Maybe it should be RetoSwap.

**Comment by balz666** [comment]
At least it launches for you. I am stuck with a grey window named "Untitled window" and it shows as "Haveno" in Task Manager, but simply won't launch.

**Comment by slrslr** [comment]
@balz666 try to launch it via command line and see if you can find the log file (path may be displayed when you submit new github issue). Maybe it will show some details of the issue.

**Comment by balz666** [comment]
> @balz666 try to launch it via command line and see if you can find the log file (i do not see mentioned what are the paths cross-platform). Submit new github issue.

How can I do that exactly?

**Comment by slrslr** [comment]
Ask search engine (internet, your computer) or AI. Regarding issue, https://github.com/retoaccess1/haveno-reto/issues/new/choose

**Comment by balz666** [comment]
OK I was able to launch it from terminal. Here is the message I got:

> Dec-19 14:47:13.605 [JavaFX Application Thread] ERROR haveno.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread, error=Input stream must not be null
 java.lang.NullPointerException: Input stream must not be null
	at javafx.graphics/javafx.scene.image.Image.validateInputStream(Unknown Source)
	at javafx.graphics/javafx.scene.image.Image.<init>(Unknown Source)
	at haveno.desktop.util.ImageUtil.getImageByUrl(ImageUtil.java:52)
	at haveno.desktop.util.ImageUtil.getImageByPath(ImageUtil.java:70)
	at haveno.desktop.app.HavenoAppMain$PasswordDialog.<init>(HavenoAppMain.java:203)
	at haveno.desktop.app.HavenoAppMain.lambda$loginAccount$1(HavenoAppMain.java:174)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

java.lang.NullPointerException: Input stream must not be null
	at javafx.graphics/javafx.scene.image.Image.validateInputStream(Unknown Source)
	at javafx.graphics/javafx.scene.image.Image.<init>(Unknown Source)
	at haveno.desktop.util.ImageUtil.getImageByUrl(ImageUtil.java:52)
	at haveno.desktop.util.ImageUtil.getImageByPath(ImageUtil.java:70)
	at haveno.desktop.app.HavenoAppMain$PasswordDialog.<init>(HavenoAppMain.java:203)
	at haveno.desktop.app.HavenoAppMain.lambda$loginAccount$1(HavenoAppMain.java:174)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Dec-19 14:47:13.627 [JavaFX Application Thread] WARN  haveno.desktop.app.HavenoApp: Scene not available yet, we create a new scene. The bug might be caused by an exception in a constructor or by a circular dependency in Guice. throwable=java.lang.NullPointerException: Input stream must not be null

**Comment by retoaccess1** [comment]
Install latest version for fix (v16).
